= grepp(1)

== NAME

grepp - An improved version of the most common combinations of grep, find (and
sed, see Roadmap) in a single script.

== SYNOPSYS

*grepp* [*-i*] [*-l*] [*-I*] [*-n*] 'pattern' ['location'] [*--fullpath*]
    [*--name*|*--iname* 'file_pattern'] [*-v* | *--ignore* 'file_pattern']
    [*--color* 'never'|'auto'|'always'] [*--spacing*]
    [*--pp*|*--prerocessor* 'program' *--ppo* 'program options after filename']

*grepp* [*-h* |*-?*] # Short help

*grepp* [*--help*] # Extended help

*command* | *grepp* [options] 'pattern' # pipe usage

== DESCRIPTION

An improved version of the most common combinations of *grep*, *find* (and
*sed*, see Roadmap) in a single script.

It will save you time typing and copying (see Why grep's ouptut sucks) and
it uses 'REGEX' in your patterns.

greps 'pattern' recursively from current dir or 'location' in every file except
for files in the git ignore file (TODO, see Roadmap) or given by the
cmdline option. It also can filter by 'file pattern'.

It is inspired in grep and find, but unlike grep it doesn't print a colon +:+
divider after the file name since that makes it annoying to double click
to select.

It automatically pipes the output to your environment *PAGER* or to *less* if
no environment value is set.

== OPTIONS

'pattern':: Pattern to grep for (In regex syntax).

'location':: Location to search in.

*-i*:: Ignore case.

*-l*:: Print file name only.

*-I*:: Ignore binary files.

*--name* | *--iname* 'file_pattern'::

Filter result to match only things that match 'file_pattern'. *iname* does case
insensitive matching.

*-v* | *--ignore* 'file_pattern'::

Filter result to additionally ignore files that match 'file_pattern'. Case
insensitive.

*--spacing*::

Print original spacing. By default initial spacing is ignored.

*--fullpath*::

Print full paths for matching files.

*--color* 'never'|'auto'|'always'::

Select color use: never, auto (default), always.

*--preprocessor* | *--pp* 'program'::

Run each file by a preprocessor program before searching for matches.
+
Example:

  grepp pattern --iname '\.pdf' --preprocessor pdftotext --ppo '-'
+
To run each file with '.pdf' extention through the
'pdftotext' program to convert pdf files to text using pdftotext before
grepping.
+
When using the *--preprocessor* option the *BINARY* filtering is disabled, you
should filter results by filename extension using *--name* or *--iname*.

*--preprocessor-options* | *--ppo* 'program options after filename'::

Use this option to pass preprocessor options that MUST go after the filename,
if you are using options that go before the filename then pass them in the
*--preprocessor* option.

*--context* 'number'::

Number of lines of context to use. It implies *--spacing*.
+
TODO: Only precontext is implemented

*-m* | *--multi* 'number'::

Allow grepping for regex in multiple lines. `\n` gets changed into space.
'number' determines how many lines plus one to look for.

== Why grep's ouptut sucks

grep prints a colon +:+ divider after the file name since that makes it
annoying to double click to select.

TODO: images here

== Roadmap

* Git ignore checking (waiting for ubuntu release of git 1.8.2)
* search (done) and replace (missing)
* post context

== Source code

github: <https://github.com/DavidGamba/grepp>

== License

Copyright (C) 2012-2013 David Gamba. All rights reserved. This program is free
software; you can redistribute it and/or modify it under the same terms as Perl
itself.
