= grepp(1)

== Name

grepp - An improved version of the most common combinations of grep, find (and
sed, see Roadmap) in a single script.

== Synopsys

*grepp* [*most grep options*] 'pattern' ['location']
      [*--if* | *--ignore-file* 'file_pattern'] [*--spacing*]

*grepp* [*-h* |*-?*] # Short help

*grepp* [*--help*] # Extended help

*command* | *grepp* [options] 'pattern' # pipe usage

== Description
greps 'pattern' recursively from current dir or 'location' in every file
except for files in the git ignore file or given by the cmdline option.

It is inspired in grep, but unlike grep it doesn't print a *:*
divider right after the file name since that makes it annoying to double click
to select, it adds a space before and after the *:* divider.

As it is expected, the color only shows when the ouput is not being
piped. See *--color* for more details.

It automatically pipes the output to your environment *PAGER* or to *less* if
no environment value is set.

== Options

'pattern'::

Pattern to grep for (In regex syntax).

'location'::

Location to search in. By default it will use the current directory.

*-i*:: Ignore case.

*-l*:: Print file name only.

*-I*:: Ignore binary files.

*TODO* *--name* | *--iname* 'file_pattern'::

filter result to match only things that match 'file_pattern'. *iname* does case
insensitive matching.

*--if* | *--ignore-file* 'file_pattern'::

Ignore files matching 'file_pattern' regex. Can be used more than one.
Case insensitive.

*TODO* *--fullpath*::

Print full paths for matching files.

*--spacing*::

Print original spacing. By default initial spacing is ignored.

*--color* 'never'|'auto'|'always'::

Select color use: never, auto (default), always.

== Why grep's ouptut sucks

grep prints a colon +:+ divider after the file name since that makes it
annoying to double click to select.

TODO: images here

== Roadmap

* Fine tune git grep usage
* search (done) and replace (missing)

== Source code

github: <https://github.com/DavidGamba/grepp>

== License

Copyright (C) 2012-2014 David Gamba. All rights reserved. This program is free
software; you can redistribute it and/or modify it under the same terms as Perl
itself.
